encoding: bom|utf-8

title: Киа Бонго
phone: +7 (846) 221-90-59
description: >- # this means to ignore newlines until "baseurl:"
  Покупка Kia Bongo в Самаре. Корейские грузовики Kia для предпринимателей и частных компаний. Проверенные авто с гарантией в Kia-Comtrans.ru Тел: +7 (960) 824-98-66
baseurl: ""
# baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - mix-manifest.json
  - package.json
  - src
  - webpack.mix.js
  - yarn.lock
  - docker-compose.yml
  - package-lock.json
  - tailwind.config.js